### ISSUE TITLE
Random game crash

### ISSUE THREAD

**Issue by GerwinT03** [dvitski/companion#22]
The game randomly crashes for me sometimes with this stack trace leading back to mccic

```
java.lang.NumberFormatException: For input string: "#?"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at dev.andante.mccic.api.client.tracker.GameTracker.lambda$updateTime$1(GameTracker.java:135)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at dev.andante.mccic.api.client.tracker.GameTracker.updateTime(GameTracker.java:131)
	at dev.andante.mccic.api.client.tracker.GameTracker.onWorldTick(GameTracker.java:57)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:108)
	at net.minecraft.class_638.handler$zig000$tickWorldAfterBlockEntities(class_638.java:1633)
	at net.minecraft.class_638.method_18116(class_638.java:257)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)
```

**Comment by dvitski** [comment]
I believe I've found the root of the issue. Testing and releasing a patch soon.
